# Generated by Django 4.0.4 on 2022-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(max_length=255)),
                ('yaw_axis', models.IntegerField()),
                ('roll_axis', models.IntegerField()),
                ('throttle_axis', models.IntegerField()),
                ('pitch_axis', models.IntegerField()),
            ],
        ),
    ]
